### ISSUE TITLE
/customers/:id is buggy

### ISSUE THREAD

**Issue by ashleygwilliams** [artisan-tattoo/assistant-frontend#43]
requests to `/customers/:id` are not authed unless they are accessed via `/customers`

**Comment by ashleygwilliams** [comment]
```
GET http://localhost:8080/v1/customers/%5Bobject%20Object%5D 404 (Not Found)
ember.debug.js:28234 Error while processing route: customer Adapter operation failed Error: Adapter operation failed
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:24486:21)
    at Error.ember$data$lib$adapters$errors$$AdapterError (http://localhost:4200/assets/vendor.js:68827:50)
    at ember$data$lib$system$adapter$$default.extend.handleResponse (http://localhost:4200/assets/vendor.js:70518:16)
    at ember$data$lib$system$adapter$$default.extend.ajax.Ember.RSVP.Promise.hash.error (http://localhost:4200/assets/vendor.js:70614:33)
    at jQuery.Callbacks.fire (http://localhost:4200/assets/vendor.js:3301:30)
    at Object.jQuery.Callbacks.self.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:3413:7)
    at done (http://localhost:4200/assets/vendor.js:8468:14)
    at XMLHttpRequest.jQuery.ajaxTransport.send.callback (http://localhost:4200/assets/vendor.js:8807:9)
```

**Comment by steveklabnik** [comment]
This has been mysteriously fixed
